//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceLibraryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANCER
    {
        public int ID { get; set; }
        public Nullable<int> CLUB_ID { get; set; }
        public string Fullname { get; set; }
        public int Sex { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Class_Lat { get; set; }
        public Nullable<int> Class_St { get; set; }
        public Nullable<int> Year_of_birth { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual CLASS CLASS1 { get; set; }
        public virtual CLUB CLUB { get; set; }
        public virtual SEX SEX1 { get; set; }
    }
}
