//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanceLibraryEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanceSportSimplifiedEntities : DbContext
    {
        public DanceSportSimplifiedEntities()
            : base("name=DanceSportSimplifiedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS> CLASSes { get; set; }
        public virtual DbSet<CLUB> CLUBs { get; set; }
        public virtual DbSet<COMPETITION> COMPETITIONs { get; set; }
        public virtual DbSet<DANCER> DANCERs { get; set; }
        public virtual DbSet<SEX> SEXes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
